import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

const cabinetGrotesk = localFont({
  src: "../public/fonts/CabinetGrotesk-Medium.otf",
  variable: "--font-primary",
  weight: "500",
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-secondary",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${cabinetGrotesk.variable} ${montserrat.variable} h-full scroll-smooth antialiased max-md:snap-y max-md:snap-mandatory`}
    >
      <body className="min-h-full flex flex-col max-md:snap-y max-md:snap-mandatory">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
